function S_out = fnRotirajSKvaternionom(S_in,q)

q_vMatriki = [q(1) -q(4) q(3);...
              q(4) q(1) -q(2);...
              -q(3) q(2) q(1)];

q1 = [-q(2) -q(3) -q(4); q_vMatriki];
q2 = [-q(2) q_vMatriki(1,:);...
      -q(3) q_vMatriki(2,:);...
      -q(4) q_vMatriki(3,:);];

S_out = S_in*q2*q1;